ALTER TABLE `Filter_list` ADD `comment` VARCHAR(250) NULL DEFAULT NULL AFTER `name`;
ALTER TABLE `Filter_list` CHANGE `name` `name` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL;
ALTER TABLE `Group_list` CHANGE `group_name` `group_name` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL;
ALTER TABLE `Group_list` ADD `comment` VARCHAR(250) NULL DEFAULT NULL AFTER `group_name`;
ALTER TABLE `mac_history` ADD `dhcp_hostname` VARCHAR(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL AFTER `auth_id`;
ALTER TABLE `auth_rules` ADD `comment` VARCHAR(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL AFTER `rule`;
ALTER TABLE `building` CHANGE `comment` `comment` VARCHAR(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL;
UPDATE `config_options` SET `default_value` = '/usr/local/scripts/sync_mikrotik.pl' WHERE `config_options`.`id` = 37;
ALTER TABLE `dhcp_log` ADD `dhcp_hostname` VARCHAR(250) NULL DEFAULT NULL AFTER `auth_id`;
ALTER TABLE `OU` ADD `comment` VARCHAR(250) NULL DEFAULT NULL AFTER `ou_name`;
