ALTER TABLE `devices` ADD `device_model_id` INT NULL DEFAULT '89' AFTER `device_type`;
ALTER TABLE `User_auth` ADD `device_model_id` INT NULL DEFAULT '87' AFTER `month_quota`;
ALTER TABLE `OU` ADD `nagios_host_use` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `OU` ADD `nagios_ping` BOOLEAN NOT NULL DEFAULT TRUE AFTER `nagios_host_use`;
ALTER TABLE `OU` ADD `nagios_default_service` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `nagios_ping`;
UPDATE `OU` SET `ou_name` = '!Всё' WHERE `OU`.`id` = 0;
UPDATE `OU` SET `nagios_host_use` = 'voip' WHERE `OU`.`id` = 4;
UPDATE `OU` SET `nagios_host_use` = 'generic-host' WHERE `OU`.`id` = 0;
UPDATE `OU` SET `nagios_ping` = '0' WHERE `OU`.`id` = 5;
UPDATE `OU` SET `nagios_host_use` = 'ip-cam' WHERE `OU`.`id` = 5;
UPDATE `OU` SET `nagios_default_service` = 'printer-service' WHERE `OU`.`id` = 6;
UPDATE `OU` SET `nagios_host_use` = 'printers' WHERE `OU`.`id` = 6;
UPDATE `OU` SET `nagios_host_use` = 'switches' WHERE `OU`.`id` = 7;
UPDATE `OU` SET `nagios_host_use` = 'ups' WHERE `OU`.`id` = 8;
UPDATE `OU` SET `nagios_host_use` = 'security' WHERE `OU`.`id` = 9;
UPDATE `OU` SET `nagios_host_use` = 'routers' WHERE `OU`.`id` = 10;
UPDATE `OU` SET `nagios_host_use` = 'ap' WHERE `OU`.`id` = 12;
INSERT INTO `vendors` (`id`, `name`) VALUES ('33', 'QSC');
INSERT INTO `vendors` (`id`, `name`) VALUES ('34', 'Projectiondesign');
INSERT INTO `vendors` (`id`, `name`) VALUES ('35', 'Lenovo');
ALTER TABLE `User_auth` ADD `firmware` VARCHAR(100) NULL DEFAULT NULL AFTER `device_model_id`;
ALTER TABLE `devices` ADD `firmware` VARCHAR(100) NULL DEFAULT NULL AFTER `device_model_id`;
