ALTER TABLE `devices` ADD `device_model_id` INT NULL DEFAULT NULL AFTER `device_type`;
ALTER TABLE `User_auth` ADD `device_model_id` INT NULL DEFAULT NULL AFTER `month_quota`;
ALTER TABLE `OU` ADD `nagios_host_use` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `OU` ADD `nagios_ping` BOOLEAN NOT NULL DEFAULT TRUE AFTER `nagios_host_use`;
ALTER TABLE `OU` ADD `nagios_default_service` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `nagios_ping`;
UPDATE `OU` SET `ou_name` = '!Всё' WHERE `OU`.`id` = 0;
UPDATE `OU` SET `nagios_template` = 'voip' WHERE `OU`.`id` = 4;
UPDATE `OU` SET `nagios_template` = 'generic-host' WHERE `OU`.`id` = 0;
UPDATE `OU` SET `nagios_ping` = '0' WHERE `OU`.`id` = 5;
UPDATE `OU` SET `nagios_template` = 'ip-cam' WHERE `OU`.`id` = 5;
UPDATE `OU` SET `nagios_default_service` = 'printer-service' WHERE `OU`.`id` = 6;
UPDATE `OU` SET `nagios_template` = 'printers' WHERE `OU`.`id` = 6;
UPDATE `OU` SET `nagios_template` = 'switches' WHERE `OU`.`id` = 7;
UPDATE `OU` SET `nagios_template` = 'ups' WHERE `OU`.`id` = 8;
UPDATE `OU` SET `nagios_template` = 'security' WHERE `OU`.`id` = 9;
UPDATE `OU` SET `nagios_template` = 'routers' WHERE `OU`.`id` = 10;
UPDATE `OU` SET `nagios_template` = 'ap' WHERE `OU`.`id` = 12;
INSERT INTO `vendors` (`id`, `name`) VALUES (33, 'QSC');
ALTER TABLE `devices` CHANGE `device_model_id` `device_model_id` INT NULL DEFAULT '89';
ALTER TABLE `User_auth` CHANGE `device_model_id` `device_model_id` INT(11) NULL DEFAULT '87';
INSERT INTO `vendors` (`id`, `name`) VALUES ('34', 'Projectiondesign');
INSERT INTO `vendors` (`id`, `name`) VALUES ('35', 'Lenovo');
