#!/bin/bash

mv IncludeBrasHeader.txt IncludeHeaderBras.txt
sed -i 's/IncludeBrasHeader/IncludeHeaderBras/' *.txt

mv IncludeBuildingHeader.txt IncludeHeaderBuilding.txt
sed -i 's/IncludeBuildingHeader/IncludeHeaderBuilding/' *.txt

mv IncludeClavHeader.txt IncludeHeaderClav.txt
sed -i 's/IncludeClavHeader/IncludeHeaderClav/' *.txt

mv IncludeDhcpPoolHeader.txt IncludeHeaderDhcpPool.txt
sed -i 's/IncludeDhcpPoolHeader/IncludeHeaderDhcpPool/' *.txt

mv IncludeGatewayHeader.txt IncludeHeaderGateway.txt
sed -i 's/IncludeGatewayHeader/IncludeHeaderGateway/' *.txt

mv IncludeNetDevHeader.txt IncludeHeaderNetDev.txt
sed -i 's/IncludeNetDevHeader/IncludeHeaderNetDev/' *.txt

mv IncludeRackHeader.txt IncludeHeaderRack.txt
sed -i 's/IncludeRackHeader/IncludeHeaderRack/' *.txt

mv IncludeRoomHeader.txt IncludeHeaderRoom.txt
sed -i 's/IncludeRoomHeader/IncludeHeaderRoom/' *.txt

mv IncludeRouterHeader.txt IncludeHeaderRouter.txt
sed -i 's/IncludeRouterHeader/IncludeHeaderRouter/' *.txt

mv IncludeServerHeader.txt IncludeHeaderServer.txt
sed -i 's/IncludeServerHeader/IncludeHeaderServer/' *.txt

mv IncludeSnmpPortHeader.txt IncludeHeaderSnmpPort.txt
sed -i 's/IncludeSnmpPortHeader/IncludeHeaderSnmpPort/' *.txt

mv IncludeSubnetHeader.txt IncludeHeaderSubnet.txt
sed -i 's/IncludeSubnetHeader/IncludeHeaderSubnet/' *.txt

mv IncludeSwitchHeader.txt IncludeHeaderSwitch.txt
sed -i 's/IncludeSwitchHeader/IncludeHeaderSwitch/' *.txt

mv IncludeUpsHeader.txt IncludeHeaderUps.txt
sed -i 's/IncludeUpsHeader/IncludeHeaderUps/' *.txt

mv IncludeShowAtss.txt IncludeFindAtss.txt
mv IncludeShowAtssDisabled.txt IncludeFindAtssDisabled.txt
sed -i 's/IncludeShowAtss/IncludeFindAtss/' *.txt

mv IncludeShowAuth.txt IncludeFindAuth.txt
mv IncludeShowAuthAll.txt IncludeFindAuthAll.txt
sed -i 's/IncludeShowAuth/IncludeFindAuth/' *.txt

mv IncludeShowCerts.txt IncludeFindCerts.txt
sed -i 's/IncludeShowCerts/IncludeFindCerts/' *.txt

mv IncludeShowPhones.txt IncludeFindPhones.txt
mv IncludeShowPhonesDisabled.txt IncludeFindPhonesDisabled.txt
sed -i 's/IncludeShowPhones/IncludeFindPhones/' *.txt

mv IncludeShowServers.txt IncludeFindServers.txt
sed -i 's/IncludeShowServers/IncludeFindServers/' *.txt

mv IncludeShowServices.txt IncludeFindServices.txt
sed -i 's/IncludeShowServices/IncludeFindServices/' *.txt

mv IncludeShowSites.txt IncludeFindSites.txt
sed -i 's/IncludeShowSites/IncludeFindSites/' *.txt

mv IncludeShowVms.txt IncludeFindVms.txt
sed -i 's/IncludeShowVms/IncludeFindVms/' *.txt

mv IncludeShowVoipGates.txt IncludeFindVoipGates.txt
sed -i 's/IncludeShowVoipGates/IncludeFindVoipGates/' *.txt

mv IncludeShowVoipGatesDisabled.txt IncludeFindVoipGatesDisabled.txt
sed -i 's/IncludeShowVoipGatesDisabled/IncludeFindVoipGatesDisabled/' *.txt

mv IncludePhoneList.txt IncludeFindPhoneList.txt
sed -i 's/IncludePhoneList/IncludeFindPhoneList/' *.txt

mv IncludeCamList.txt IncludeFindCamList.txt
sed -i 's/IncludeCamList/IncludeFindCamList/' *.txt

mv IncludeATSPhoneList.txt IncludeFindATSPhoneList.txt
sed -i 's/IncludeATSPhoneList/IncludeFindATSPhoneList/' *.txt

mv IncludeWPapList.txt IncludeFindWPapList.txt
sed -i 's/IncludeWPapList/IncludeFindWPapList/' *.txt

exit
