UPDATE `config_options` SET `description` = 'Еденица измерения трафика - Килобайт (0) или кибибайт (1,default)' WHERE `config_options`.`id` = 1;
UPDATE `config_options` SET `type` = 'bool' WHERE `config_options`.`id` = 1;
UPDATE `config_options` SET `max_value` = '1' WHERE `config_options`.`id` = 1;
UPDATE `config_options` SET `min_value` = '1' WHERE `config_options`.`id` = 1;
UPDATE `config_options` SET `description` = 'Создавать ли новые записи для неизвестных адресов из анализа трафика netflow. Не включать, если netflow снимает данные с маршрутизатора локальной сети' WHERE `config_options`.`id` = 22;
UPDATE `config` SET `value` = '0' WHERE `config`.`id` = 1 and `config`.`value` = 1000;
UPDATE `config` SET `value` = '1' WHERE `config`.`id` = 1 and `config`.`value` = 1024;
ALTER TABLE `config_options` CHANGE `description` `description.russian` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL;
ALTER TABLE `config_options` ADD `description.english` TEXT NULL DEFAULT NULL AFTER `description.russian`;
UPDATE `config_options` set `description.english` = "Traffic measurement unit - Kilobyte (1000b) or kibibyte (1024b,default)" WHERE `id`=1;
UPDATE `config_options` set `description.english` = "DNS server ip address" WHERE `id`=3;
UPDATE `config_options` set `description.english` = "ip address of the DHCP server" WHERE `id`=5;
UPDATE `config_options` set `description.english` = "The default version of snmp. Currently, 1 and 2 are supported. Support for version 3 is in development." WHERE `id`=9;
UPDATE `config_options` set `description.english` = "Read snmp community by default" WHERE `id`=11;
UPDATE `config_options` set `description.english` = "Poll the mac table of switches when scanning the network. If the option is disabled, it will be impossible to map the ip address to the switch port" WHERE `id`=17;
UPDATE `config_options` set `description.english` = "Perform a scan of the router arp table when scanning the network. If the option is disabled, mapping the mac address to the ip address be possible only from the logs of the dhcp server." WHERE `id`=19;
UPDATE `config_options` set `description.english` = "Administrator e-mail" WHERE `id`=21;
UPDATE `config_options` set `description.english` = "Whether to create new records for unknown addresses from netflow traffic analysis. Do not enable if netflow get data from the local network router" WHERE `id`=22;
UPDATE `config_options` set `description.english` = "Whether to keep the details of traffic from netflow by ip addresses of users" WHERE `id`=23;
UPDATE `config_options` set `description.english` = "Depth of detail storage in days. Setting a value greater than 3-7 days will cause the database to grow and increase the time about to display details in the admin interface" WHERE `id`=26;
UPDATE `config_options` set `description.english` = "Storage depth of the dhcp server lease" WHERE `id`=27;
UPDATE `config_options` set `description.english` = "Login to Mikrotik routers to manage the dhcp server and access control" WHERE `id`=28;
UPDATE `config_options` set `description.english` = "Password to log in to Mikrotik routers for managing the dhcp server and access control" WHERE `id`=29;
UPDATE `config_options` set `description.english` = "Router ssh port" WHERE `id`=30;
UPDATE `config_options` set `description.english` = "Organization name" WHERE `id`=32;
UPDATE `config_options` set `description.english` = "Organization domain" WHERE `id`=33;
UPDATE `config_options` set `description.english` = "Enable debugging" WHERE `id`=34;
UPDATE `config_options` set `description.english` = "Storage time of the history of connection locations of ip addresses" WHERE `id`=35;
UPDATE `config_options` set `description.english` = "Location of the access control script for Mikrotik routers" WHERE `id`=37;
UPDATE `config_options` set `description.english` = "Location of the dhcp server configuration management script" WHERE `id`=38;
UPDATE `config_options` set `description.english` = "Location of the dns server management script" WHERE `id`=39;
UPDATE `config_options` set `description.english` = "Location of the Nagios configuration script" WHERE `id`=40;
UPDATE `config_options` set `description.english` = "Location of the network scan script" WHERE `id`=41;
UPDATE `config_options` set `description.english` = "Do not write the event log of the hotspot dhcp server. It makes sense to include it, since the rental time in the hotspot is usually small and the logs of ordinary users become invisible in the hotspot records" WHERE `id`=44;
UPDATE `config_options` set `description.english` = "Do not write events for updating the IP address of the dhcp server. " WHERE `id`=45;
UPDATE `config_options` set `description.english` = "Update the hostname in DNS when receiving the address via DHCP" WHERE `id`=46;
UPDATE `config_options` set `description.english` = "Depth of work logs storage in the admin interface" WHERE `id`=47;
UPDATE `config_options` set `description.english` = "Syslog server logs storage depth" WHERE `id`=48;
UPDATE `config_options` set `description.english` = "User traffic statistics storage depth" WHERE `id`=49;
UPDATE `config_options` set `description.english` = "Immediate change of access lists on the router after editing the user record " WHERE `id`=50;
UPDATE `config_options` set `description.english` = "Send e-mail messages for message levels WARNING & ERROR" WHERE `id`=51;
UPDATE `config_options` set `description.english` = "E-mail address from which mail is sent" WHERE `id`=52;
UPDATE `config_options` set `description.english` = "Each level includes the previous one:\r\n0 - ERROR - write only errors\r\n1 - WARNING - write warnings\r\n2 - INFO - write informational\r\n3 - VERBOSE - write detailed information about the operations performed " WHERE `id`=53;
UPDATE `config_options` set `description.english` = "Enable traffic quota processing" WHERE `id`=54;
UPDATE `config_options` set `description.english` = "Data reset interval from netflow collector, minutes" WHERE `id`=55;
UPDATE `config_options` set `description.english` = "The storage time of complete traffic statistics for each ip address in days. The table is 6 times larger than the usual hourly statistic Hardly anyone will need a storage depth of more than a month." WHERE `id`=56;
UPDATE `config_options` set `description.english` = "nagios site address" WHERE `id`=57;
UPDATE `config_options` set `description.english` = "cacti site address" WHERE `id`=58;
UPDATE `config_options` set `description.english` = "Torrus website address" WHERE `id`=59;
UPDATE `config_options` set `description.english` = "Wiki website address" WHERE `id`=60;
UPDATE `config_options` set `description.english` = "Path to wiki data directory" WHERE `id`=61;
UPDATE `config_options` set `description.english` = "Address of this site" WHERE `id`=62;
UPDATE `config_options` set `description.english` = "Web for Wiki. Default - Main. http://example.local/Main/WebHome" WHERE `id`=63;
UPDATE `config_options` set `description.english` = "Create an automatic binding of the mac address to the user. I.e. all ip addresses for the found mac will be bound to the same user." WHERE `id`=64;
