#!/bin/sh

#exit

[ -z "$1" ] && exit 100

fname=$1
routerid=$2

[ ! -e "${fname}" ] && exit 101

#renice +19 -p $$ >/dev/null 2>&1
/bin/nfdump -N -r ${fname} -q -o 'fmt:%tsr;%pr;%sa;%xda;%sp;%dp;%ipkt;%ibyt;%in;%out' | /usr/local/scripts/parse_flow.pl ${routerid} &

exit 0
