ALTER TABLE `config_options` ADD `default_value` TEXT NULL DEFAULT NULL AFTER `type`;

UPDATE `config_options` SET `default_value` = '1024' WHERE `config_options`.`id` = 1;
UPDATE `config_options` SET `default_value` = '127.0.0.1' WHERE `config_options`.`id` = 3;
UPDATE `config_options` SET `default_value` = '127.0.0.1' WHERE `config_options`.`id` = 5;
UPDATE `config_options` SET `default_value` = '2' WHERE `config_options`.`id` = 9;
UPDATE `config_options` SET `default_value` = 'public' WHERE `config_options`.`id` = 11;
UPDATE `config_options` SET `default_value` = '1' WHERE `config_options`.`id` = 17;
UPDATE `config_options` SET `default_value` = '1' WHERE `config_options`.`id` = 19;
UPDATE `config_options` SET `default_value` = '1' WHERE `config_options`.`id` = 20;
UPDATE `config_options` SET `default_value` = '0' WHERE `config_options`.`id` = 22;
UPDATE `config_options` SET `default_value` = '1' WHERE `config_options`.`id` = 23;
UPDATE `config_options` SET `default_value` = '3' WHERE `config_options`.`id` = 26;
UPDATE `config_options` SET `default_value` = '1' WHERE `config_options`.`id` = 27;
UPDATE `config_options` SET `description` = 'Глубина хранения аренды dhcp-сервера' WHERE `config_options`.`id` = 27;
UPDATE `config_options` SET `default_value` = 'admin' WHERE `config_options`.`id` = 28;
UPDATE `config_options` SET `default_value` = '23' WHERE `config_options`.`id` = 30;
UPDATE `config_options` SET `default_value` = 'ORG' WHERE `config_options`.`id` = 32;
UPDATE `config_options` SET `default_value` = 'local' WHERE `config_options`.`id` = 33;
UPDATE `config_options` SET `default_value` = '0' WHERE `config_options`.`id` = 34;
UPDATE `config_options` SET `default_value` = '90' WHERE `config_options`.`id` = 35;
UPDATE `config_options` SET `default_value` = '0' WHERE `config_options`.`id` = 36;
UPDATE `config_options` SET `description` = 'Удалять ли старые записи ip-адресов в динмамическом пуле (у юзера default)' WHERE `config_options`.`id` = 36;
UPDATE `config_options` SET `default_value` = '/usr/local/scripts/fetch_new_arp.pl' WHERE `config_options`.`id` = 41;
UPDATE `config_options` SET `default_value` = '/usr/local/scripts/sync_user_list.pl' WHERE `config_options`.`id` = 37;
UPDATE `config_options` SET `default_value` = '/usr/local/scripts/update-dnsmasq' WHERE `config_options`.`id` = 38;
UPDATE `config_options` SET `default_value` = '/etc/nagios/restart_nagios' WHERE `config_options`.`id` = 40;
UPDATE `config_options` SET `default_value` = '/usr/local/scripts/update-dns' WHERE `config_options`.`id` = 39;
UPDATE `config_options` SET `default_value` = '1' WHERE `config_options`.`id` = 43;
UPDATE `config_options` SET `default_value` = '1' WHERE `config_options`.`id` = 44;
UPDATE `config_options` SET `default_value` = '0' WHERE `config_options`.`id` = 45;
UPDATE `config_options` SET `default_value` = '0' WHERE `config_options`.`id` = 46;
UPDATE `config_options` SET `default_value` = '90' WHERE `config_options`.`id` = 47;
UPDATE `config_options` SET `default_value` = '90' WHERE `config_options`.`id` = 48;
UPDATE `config_options` SET `default_value` = '365' WHERE `config_options`.`id` = 49;
